### We'll have a list of collaborators with a specified role in a variable referred to by cllbrtrs_var variable.
---
- name: "Get all {{ repo_name }}'s {{ affiliation }} collaborators"
  when: page == 1 or response.json | length > 0
  loop: "{{ github_pages }}"
  loop_control:
    loop_var: page
  uri:
    headers:
      Authorization: "token {{ github_token }}"
    url: "{{ github_api }}/repos/{{ github_org }}/{{ repo_name }}/collaborators\
      ?per_page={{ github_per_page }}\
      &page={{ page }}\
      &affiliation={{ affiliation }}"
  register: response

- name: Initialize the list of collaborators with an empty list
  set_fact:
    cllbrtrs: []

- name: "Dump all the {{ response | json_query('results[*].json[*]') | flatten | length }} {{ repo_name }} repo's {{ affiliation }} collaborators"
  when: affiliation == 'direct'
  loop: "{{ response | json_query('results[*].json[*][login]') | flatten }}"
  loop_control:
    loop_var: collaborator
  set_fact:
    cllbrtrs: "{{ cllbrtrs + username }}"
  vars:
    query: "[? value.github == '{{ collaborator }}'].key"
    username: "{{ lookup('dict', users, wantlist=true) | json_query(query) }}" # a list of zero or one element

- name: "Dump all the {{ response | json_query('results[*].json[*]') | flatten | length }} {{ repo_name }} repo's {{ affiliation }} collaborators"
  when: affiliation == 'outside'
  set_fact:
    cllbrtrs: "{{ response | json_query('results[*].json[*][login]') | flatten }}"

- name: "Jot down all {{ cllbrtrs | length }} {{ repo_name }}'s {{ affiliation }} collaborators into the {{ cllbrtrs_var }} variable"
  set_fact: "{{ cllbrtrs_var }}={{ cllbrtrs }}"
