---
- name: Initialize members list with an empty value
  set_fact:
    mmbrs: []

- name: "Get all {{ team_slug }} team's {{ role }}s"
  when: page == 1 or response.json | length > 0
  loop: "{{ github_pages }}"
  loop_control:
    loop_var: page
  uri:
    headers:
      Authorization: "token {{ github_token }}"
    url: "{{ github_api }}/orgs/{{ github_org }}/teams/{{ team_slug }}/members\
      ?per_page={{ github_per_page }}\
      &page={{ page }}\
      &role={{ role }}"
  register: response

- name: "Dump all the {{ response | json_query('results[*].json[*]') | flatten | length }} {{ team_slug }} team's {{ role }}s"
  loop: "{{ response | json_query('results[*].json[*][login]') | flatten }}"
  loop_control:
    loop_var: member
  set_fact:
    mmbrs: "{{ mmbrs + username }}"
  vars:
    query: "[? value.github == '{{ member }}'].key"
    username: "{{ lookup('dict', users, wantlist=true) | json_query(query) }}" # a list of zero or one element

- name: "Jot down all {{ mmbrs | length }} {{ team_slug }}'s {{ role }}s into the {{ mmbrs_var }} variable"
  set_fact: "{{ mmbrs_var }}={{ mmbrs }}"
